### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by Praxthisnovcht** [xpyctum/PlayerStats#1]
Hi!

I wonder if we could try to created a link between your plugin and CustomChat to display the counter kill and murder.

Sincerely Prax,: D

**Comment by xpyctum** [comment]
Hm, it's interesting. I create api for my plugin

**Comment by xpyctum** [comment]
Now going to create API

**Comment by xpyctum** [comment]
Added api part for get deaths

**Comment by Praxthisnovcht** [comment]
do not know how to make it work with CustomChat = '(

**Comment by xpyctum** [comment]
Yep, use this,
Server::getInstance()->getPluginManager()->getPlugin("PlayerStats")->getDeaths($player);

**Comment by Praxthisnovcht** [comment]
could you look xD
 I managed to insert my private plugin in a mode of xp and level but I have struggled too ....

**Comment by xpyctum** [comment]
Try this https://github.com/xpyctum/PlayerStats/wiki/Wiki-page

**Comment by xpyctum** [comment]
Where you upload plugin with code for me?

**Comment by Praxthisnovcht** [comment]
did not understand x

**Comment by xpyctum** [comment]
$val = Server::getInstance()->getPluginManager()->getPlugin("PlayerStats")->getDeaths($player);
this insert in your code

**Comment by Praxthisnovcht** [comment]
after just replace? 
I pretty novice xd

**Comment by Praxthisnovcht** [comment]
I do not think omg
 it's very simple: D
 must have eaten too much

**Comment by xpyctum** [comment]
But this works.

**Comment by xpyctum** [comment]
This must return deaths of your player. -_- 
Next your dream.
